### PR TITLE
Issue-31 endpoint for getting all print jobs

### PR DESCRIPTION
**Pull request by kaansonmezoz**
Refactoring. Requests moved to dto/request, responses moved to dto/response

Response class has been created for GET request

Endpoint for get all print jobs has been created

### CODE REVIEW

**Comment by kaansonmezoz** [comment]
Sure :)

**Comment by kaansonmezoz** [comment]
Done :)

**Comment by Will-Estes** [comment]
Hi Kaan

Nice job with the refactoring you've done.

Everything looks good except for the PrintJobControllerTest: 
- You've removed the previously existing tests. You'll need to add back the test coverage of the removed tests with your refactored class. 
- Didn't add a "Sad Path" (fail) test for your new code. I'm thinking it should return an empty array of printJobs[ ] if no print jobs are available.  

-Will

**Comment by kaansonmezoz** [comment]
Hi Wİll, 
- Instead of empty array i thiink it will be better if I just HttpStatus.NO_CONTENT or HttpStatus.NOT_FOUND.
- Also I was thinking to create failing tests after I implemented ExceptionHandler. There will be too many changes in the code so it will make a bit harder to resolve conflicts and understand the code. So I'm going to create new branch called feature/ISSUE-NUMBER-exception-handler

**Comment by Will-Estes** [comment]
Hi Kaan,
I was up in the air about returning a status message or returning a blank array, so if you think a status is better (I'm thinking 404) then let's roll with that. 
I'm okay with the failing tests being done a little later. Please put a TODO for this in the test class. 

It looks like there's some merge conflicts. So please merge master and add the test coverage and I'll approve this request. 

Thanks!

**Comment by kaansonmezoz** [comment]
Conflicts have been resolved.

**Comment by Will-Estes** [comment]
Hi Kaan,
It looks like you got your .idea files pushed up by mistake. Can you please remove them? Everything else looks good, so when you get the .idea issue fixed, we'll merge this.
Thanks!

**Comment by kaansonmezoz** [comment]
Done

**Pull request merged**
