### PR TITLE
Fix : PrintJobOperations | newPrintJob | Update employee lookup to on…

### PR DESCRIPTION
**Pull request by Divya-Tamilazhagan**
…ly use employees already in the database #165

### CODE REVIEW

**Comment by Divya-Tamilazhagan** [comment]
what is the reason for rejection of PR?

**Comment by Divya-Tamilazhagan** [comment]
what is the reason for rejection of PR?

**Comment by jberns** [comment]
Hi @Divya-Tamilazhagan, Looks like one of the print job tests failed.  I can look into in more detail tomorrow but I would guess that the way the mocks are setup, the email object is not being populated properly and throwing an error.

**Comment by jberns** [comment]
Hi @Divya-Tamilazhagan.  Can you take a look at the tests and these lines of the `/ideaLab/Backend/src/test/java/idealab/api/operations/PrintJobOperationsTest.java` file.

```
        when(emailHashRepo.findByEmailHash(any())).thenReturn(null);
        when(emailHashRepo.save(any())).thenReturn(emailHash);
```
if you replace `null` in the first line with `emailHash` and then delete the second line this should work.

Currently because the email hash is null in the current test, it is throwing an error before it returns the print job due to the changes.

**Comment by jberns** [comment]
Going to close this.  I realized the emailHash is not part of the employee record and I fixed this as part of #214

**Pull request closed without merging**
